"""
Episode memory layer.

- Locally: SQLite (no setup, file in repo root).
- On Render: Postgres (via DATABASE_URL env var).

Single API — callers don't care which backend.
"""

import os
from contextlib import contextmanager
from dataclasses import asdict, is_dataclass
from datetime import date, datetime, timedelta
from pathlib import Path

# Pick backend based on DATABASE_URL env var
USE_POSTGRES = bool(os.environ.get("DATABASE_URL"))

if USE_POSTGRES:
    import psycopg2
    import psycopg2.extras
    DATABASE_URL = os.environ["DATABASE_URL"]
else:
    import sqlite3
    DB_PATH = Path(os.environ.get("DB_PATH", "episodes.db"))


# ───── Schema ─────
# Postgres uses SERIAL; SQLite uses INTEGER PRIMARY KEY AUTOINCREMENT.
# We swap the relevant tokens at build time.

SCHEMA_TEMPLATE = """
CREATE TABLE IF NOT EXISTS episodes (
    id            {AUTO_PK},
    date          TEXT NOT NULL,
    pillar        TEXT NOT NULL,
    topic_summary TEXT NOT NULL,
    transcript    TEXT,
    audio_url     TEXT,
    word_count    INTEGER,
    created_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_episodes_date ON episodes(date);
CREATE INDEX IF NOT EXISTS idx_episodes_pillar ON episodes(pillar);

CREATE TABLE IF NOT EXISTS topic_keywords (
    id         {AUTO_PK},
    episode_id INTEGER NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
    keyword    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_topic_keywords_keyword ON topic_keywords(keyword);
CREATE INDEX IF NOT EXISTS idx_topic_keywords_episode ON topic_keywords(episode_id);

CREATE TABLE IF NOT EXISTS sources (
    id          {AUTO_PK},
    episode_id  INTEGER NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
    claim       TEXT,
    source_name TEXT,
    source_url  TEXT,
    source_type TEXT,
    recency     TEXT
);

CREATE INDEX IF NOT EXISTS idx_sources_episode ON sources(episode_id);
"""

if USE_POSTGRES:
    SCHEMA = SCHEMA_TEMPLATE.format(AUTO_PK="SERIAL PRIMARY KEY")
else:
    SCHEMA = SCHEMA_TEMPLATE.format(AUTO_PK="INTEGER PRIMARY KEY AUTOINCREMENT")


# ───── Connection ─────

@contextmanager
def _connect():
    """Backend-agnostic connection context manager."""
    if USE_POSTGRES:
        conn = psycopg2.connect(DATABASE_URL)
        conn.cursor_factory = psycopg2.extras.RealDictCursor
        try:
            yield conn
        finally:
            conn.close()
    else:
        conn = sqlite3.connect(DB_PATH)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")
        try:
            yield conn
        finally:
            conn.close()


def _placeholder():
    """Returns SQL parameter placeholder for the active backend."""
    return "%s" if USE_POSTGRES else "?"


def init_db():
    """Idempotently create tables and indexes."""
    with _connect() as conn:
        cur = conn.cursor()
        if USE_POSTGRES:
            cur.execute(SCHEMA)
        else:
            cur.executescript(SCHEMA)
        conn.commit()


# ───── Helpers for backend differences ─────

def _row_to_dict(row):
    """Convert a row to dict (works for both backends)."""
    if row is None:
        return None
    return dict(row)


def _last_insert_id(cur, table: str = "episodes") -> int:
    """Returns the autogenerated id from the most recent insert."""
    if USE_POSTGRES:
        cur.execute("SELECT LASTVAL()")
        return cur.fetchone()["lastval"]
    return cur.lastrowid


# ───── Public API ─────

def save_episode(
    pillar: str,
    topic_summary: str,
    transcript: str,
    audio_url: str = "",
    sources: list | None = None,
    keywords: list[str] | None = None,
    word_count: int = 0,
    on_date: date | None = None,
) -> int:
    """Saves an episode plus its sources and keywords. Returns the new id."""
    init_db()
    on_date = on_date or date.today()
    sources = sources or []
    keywords = keywords or []
    p = _placeholder()
    
    with _connect() as conn:
        cur = conn.cursor()
        cur.execute(
            f"""INSERT INTO episodes
                (date, pillar, topic_summary, transcript, audio_url, word_count, created_at)
                VALUES ({p}, {p}, {p}, {p}, {p}, {p}, {p})""",
            (
                on_date.isoformat(),
                pillar,
                topic_summary,
                transcript,
                audio_url,
                word_count,
                datetime.now().isoformat(),
            ),
        )
        episode_id = _last_insert_id(cur)
        
        for kw in keywords:
            cur.execute(
                f"INSERT INTO topic_keywords (episode_id, keyword) VALUES ({p}, {p})",
                (episode_id, kw.strip().lower()),
            )
        
        for src in sources:
            data = asdict(src) if is_dataclass(src) else dict(src)
            cur.execute(
                f"""INSERT INTO sources
                    (episode_id, claim, source_name, source_url, source_type, recency)
                    VALUES ({p}, {p}, {p}, {p}, {p}, {p})""",
                (
                    episode_id,
                    data.get("claim", ""),
                    data.get("source_name", ""),
                    data.get("source_url", ""),
                    data.get("source_type", "unknown"),
                    data.get("recency", "unknown"),
                ),
            )
        
        conn.commit()
        return episode_id


def recent_episodes(days: int = 30) -> list[dict]:
    init_db()
    cutoff = (date.today() - timedelta(days=days)).isoformat()
    p = _placeholder()
    with _connect() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT * FROM episodes WHERE date >= {p} ORDER BY date DESC, id DESC",
            (cutoff,),
        )
        return [_row_to_dict(r) for r in cur.fetchall()]


def recent_topics(days: int = 30) -> list[str]:
    return [e["topic_summary"] for e in recent_episodes(days)]


def recent_keywords(days: int = 30) -> list[str]:
    init_db()
    cutoff = (date.today() - timedelta(days=days)).isoformat()
    p = _placeholder()
    with _connect() as conn:
        cur = conn.cursor()
        cur.execute(
            f"""SELECT DISTINCT k.keyword 
                FROM topic_keywords k
                JOIN episodes e ON e.id = k.episode_id
                WHERE e.date >= {p}
                ORDER BY k.keyword""",
            (cutoff,),
        )
        return [r["keyword"] for r in cur.fetchall()]


def pillar_last_used(pillar_name: str) -> date | None:
    init_db()
    p = _placeholder()
    with _connect() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT date FROM episodes WHERE pillar = {p} ORDER BY date DESC LIMIT 1",
            (pillar_name,),
        )
        row = cur.fetchone()
        return date.fromisoformat(row["date"]) if row else None


def pillars_used_recently(days: int = 7) -> list[str]:
    init_db()
    cutoff = (date.today() - timedelta(days=days)).isoformat()
    p = _placeholder()
    with _connect() as conn:
        cur = conn.cursor()
        cur.execute(
            f"SELECT DISTINCT pillar FROM episodes WHERE date >= {p}",
            (cutoff,),
        )
        return [r["pillar"] for r in cur.fetchall()]


def episode_count() -> int:
    init_db()
    with _connect() as conn:
        cur = conn.cursor()
        cur.execute("SELECT COUNT(*) AS count FROM episodes")
        row = cur.fetchone()
        return row["count"] if USE_POSTGRES else row[0]


# Backward-compat alias used by show_memory.py
DB_PATH_DISPLAY = "Postgres" if USE_POSTGRES else str(DB_PATH if not USE_POSTGRES else "")
